# 前言  
🎉 大家好，我是 [**大话数据分析**](https://www.heywhale.com/home/user/profile/649e7dcf7d8f7c0643ee1b93/overview)  

👨‍💻 前蚂蚁金服数据运营，现京东经营分析，专注于数据分析的实践与分享，掌握Python、SQL、PowerBI、Excel等数据分析工具，💻 擅长运用技术解决企业实际问题，欢迎一同探索数据的世界，解锁业务背后的秘密~~~  

***  

📍 [**知乎ID：大话数据分析**](https://www.zhihu.com/people/xin-cheng-jiu-meng-98)  
📍 [**公众号：大话数据分析**](https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzU3Mzk0OTIzNA==&action=getalbum&album_id=1565971278644166657&scene=126#wechat_redirect)  
📍 [**头条号：大话数据分析**](https://www.toutiao.com/c/user/token/MS4wLjABAAAA3iu5oumFbB0IeGbc06uknNN6oLHhufmmfS-HIQUR8YY/?source=mine_profile&log_from=422d4b98117c2_1734359484516)  
📍 [**小红书：大话数据分析**](https://www.xiaohongshu.com/user/profile/609ff36a0000000001007360?xsec_token=YBerBdWFqaRNr6Xrr32Fw51-FGpOsXOwRGb6SYRurvHFY=&xsec_source=app_share&xhsshare=CopyLink&appuid=609ff36a0000000001007360&apptime=1736348174&share_id=06628911520b482a9939587fee994f75)  
📍 [**哔哩哔哩：大话数据分析**](https://space.bilibili.com/343905617)  
📍 [**和鲸社区专栏：数据分析研习室**](https://www.heywhale.com/home/column/66dd887c897851404c166cfe)  

相关知识点交流 💬，论文指导 🎓️，可与我一对一交流 👨‍💻 个人微信【**Big_Data2020**】 📧 个人邮箱【**shangtianqiang@163.com**】  

👀👀👀  **【公众号：大话数据分析】** 后台回复 **【数据分析入门】** 可免费获取数据分析入门资料📚️，回复  **【加群】**  加入数据分析资料群，一起交流数据分析知识😎  

***  
# 推荐阅读  

🚀 以下内容为Python数据分析实战项目，欢迎 **Fork、点赞** 💯💯💯  


##  🗂️ Python数据分析系列文章总结  

* 📖 [**Python数据分析合集：零基础，让你轻松搞定数据分析！**](https://www.heywhale.com/mw/project/67a5b279414b53320ea67ef8)  

##  🎮️ Python入门学习  

* 👣 [**Python新手必读：数据类型、结构与控制流全总结**](https://www.heywhale.com/mw/project/67a59ce4414b53320ea29a4b)  
* 🐾 [**Python十大经典的库总结，你用过几个？**](https://www.heywhale.com/mw/project/67acc95b2248a2c0cadc6c5b)  
* 💯 [**Pandas 初学者面试题手册**](https://www.heywhale.com/mw/project/685696b376d83bc0f861d946)  
* ✨️ [**Numpy 初学者面试题手册**](https://www.heywhale.com/mw/project/68ab0515a13f8d75254f14fe)  
* 🍁 [**Python+SQL：Python环境完美支持SQL，极速数据处理！**](https://www.heywhale.com/mw/project/67af45f92248a2c0ca208425)  
* 🌟 [**学会 Python，轻松打造“互联网黑话” 生成器**](https://www.heywhale.com/mw/project/67b5dbae021c373d3a3cc158)  
* 💖 [**三行代码生成数据分析报告，Python让数据洞察一键生成！**](https://www.heywhale.com/mw/project/67daddda9a4f17f8743ec61e)  
* 🐋 [**和鲸🐋ModelWhale+DeepSeek，实现大模型智能数据分析**](https://www.heywhale.com/mw/project/67e80c57ef1abe52c12bc746)  


##  🧮 Python数据处理系列  

* 📟️ [**Python数据处理，初识Numpy与应用**](https://www.heywhale.com/mw/project/67723aacf25e67b8748f4b76)  
* 👣 [**Python数据处理，Pandas数据增删改**](https://www.heywhale.com/mw/project/67725563f42f796275c3450b)  
* 💯 [**Python数据处理，Pandas数据概览**](https://www.heywhale.com/mw/project/67725a42f25e67b874a094da)  
* ☎️ [**Python数据处理，Pandas数据清洗**](https://www.heywhale.com/mw/project/67725fd0f25e67b874a36896)  
* 🎹 [**Python数据处理，Pands数值操作**](https://www.heywhale.com/mw/project/677bc8a575b65f5e0833bd04)  
* 🖨️ [**Python数据处理，Pands数值计算**](https://www.heywhale.com/mw/project/677bd09675b65f5e08359d11)  
* 📺️ [**Python数据分析利器，Pandas实战速学教程**](https://www.heywhale.com/mw/project/68123f455e6b565a8655eb91)  


##  📊 Python数据可视化系列  

* 🎯 [**Python数据可视化，初识Matplotlib与应用**](https://www.heywhale.com/mw/project/677be433baedc637d3c0c1d5)  
* 🎮️ [**Python数据可视化，Matplotlib基础图表**](https://www.heywhale.com/mw/project/677bef9b18035c7d2e450b61)  
* 🖼️ [**Python数据可视化，Matplotlib高级图表**](https://www.heywhale.com/mw/project/677cab42baedc637d3d4cece)  
* ✨️ [**Python数据可视化，Matplotlib组合图表**](https://www.heywhale.com/mw/project/677cb8eb18035c7d2e59d84a)  
* 🎭️ [**Python数据可视化，初识Seaborn与应用**](https://www.heywhale.com/mw/project/677cf90d18035c7d2e711e3a)  
* 🎨 [**Python数据可视化，Seaborn基础图表**](https://www.heywhale.com/mw/project/677cfe6275b65f5e08652d7f)  
* 🎍 [**Python数据可视化，初识Pyecharts与应用**](https://www.heywhale.com/mw/project/67a8bca9414b53320ef4ea04)  
* 🏝️ [**Python数据可视化，Pyecharts高级图表应用**](https://www.heywhale.com/mw/project/67a8bd70414b53320ef4f0d6)  
* 🌈 [**Python数据可视化，初识Plotly与应用**](https://www.heywhale.com/mw/project/67a8bf2c8c4b5e14d99cfa86)  
* 🏖️ [**Python数据可视化，Plotly高级图表应用**](https://www.heywhale.com/mw/project/67a8c04d8c4b5e14d99d2218)  


##  🧰 Python数据分析实战  

* 👔 [**基于BOSS直聘数据，剖析数据分析岗各维度综合现状**](https://www.heywhale.com/mw/project/67e695c044b42e91ab4f4d22)  
* 🌞 [**Python异常值处理，箱线图案例使用**](https://www.heywhale.com/mw/project/67b5e463f736c0ea1e402f49)  
* 🛍️ [**Python电商综合分析案例：二八模型**](https://www.heywhale.com/mw/project/677bdb4118035c7d2e4246a8)  
* 💎 [**Python电商综合分析案例：RFM模型**](https://www.heywhale.com/mw/project/677bdfd275b65f5e0838c1d8)  
* 🔊 [**Python电商数据可视化案例，用户画像**](https://www.heywhale.com/mw/project/677d0916baedc637d3f026d0)  
* 🛒 [**Python数据分析实战：超市零售数据分析**](https://www.heywhale.com/mw/project/67f924207f6803d17779a2b1)   
* 📠 [**Python电商数据可视化案例，销售数据分析**](https://www.heywhale.com/mw/project/677d0fe575b65f5e08680e3b)  
* 📌 [**Python与K-means聚类分析：探索葡萄酒数据背后的秘密**](https://www.heywhale.com/mw/project/67506fc4b413a2b029011584)  
* 🛒 [**Python数据分析实战：利用ARIMA模型洞察股市规律**](https://www.heywhale.com/mw/project/674f1ef74e4446601cd2c71e)  
* 🏹 [**Python数据处理与可视化，二手房数据研究与分析**](https://www.heywhale.com/mw/project/66dd672620251d337705ae67)  
* 🔎 [**Python数据处理与可视化，二手房市场深度分析**](https://www.heywhale.com/mw/project/66dd7d8c20251d3377085ffa)  
* ⛳️ [**电商数据分析实战，基于双十一电商客户RFM客户分层**](https://www.heywhale.com/mw/project/65805a20827c81a4499a1024)  
* 🎬️ [**Python文本分析实战，《哪吒2》影评口碑分析**](https://www.heywhale.com/mw/project/67c1c7837c7246ffcee5d4ec)  
* 💯 [**Python数据分析实战，基于2014到2019年各省高考分数线数据**](https://www.heywhale.com/mw/project/67d81cb67a5bc9d5e3824690)  
* 🎱 [**Seaborn热力图在案例解析中的应用，以双色球数据为例**](https://www.heywhale.com/mw/project/67f1f0bc95ee59bf462a2694)  
* 🏘️ [**Python数据分析实战：基于房天下新房数据，分析上海市当前楼市情况**](https://www.heywhale.com/mw/project/68136b47324d7daa6477dfac)  


##  💻️ Python办公自动化系列  

* ☎️ [**Python办公自动化，批量提取PDF数据至Excel**](https://www.heywhale.com/mw/project/676025dfcaeff435d064000d)  
* 📑 [**Python办公自动化，批量生成合同文档**](https://www.heywhale.com/mw/project/67c5b69e176b8fd8f00361af)  
* 📝 [**Python办公自动化，批量解析文本数据**](https://www.heywhale.com/mw/project/67a74b29414b53320ed82838)  
* 📧 [**Python办公自动化，批量自动发送Email邮件**](https://www.heywhale.com/mw/project/6751ae42a7d10e6a15884728)  
* 📁 [**Python办公自动化，批量生成Excel案例数据集**](https://www.heywhale.com/mw/project/674d9ad154549b48b1286c17)  
* 🧰 [**Python办公自动化，每日自动生成数据日报**](https://www.heywhale.com/mw/project/66cc86302cadded5173bde04)  
* 📦️ [**Python办公自动化，将python代码打包为.exe程序**](https://www.heywhale.com/mw/project/67a871f4414b53320eea673f )  
* ⌨️ [**Python办公自动化，盘点打工人必备的十个Python自动化脚本**](https://www.heywhale.com/mw/project/67d41fbe3cc8f82bb02eb85d )  

##  🤖 Python机器学习系列  

* 🏢 [**Python机器学习线性回归，以房价预测案例为例**](https://www.heywhale.com/mw/project/6856a7c676d83bc0f8640d39)  
* 🚢 [**Python机器学习逻辑回归，以泰坦尼克号生存预测案例为例**](https://www.heywhale.com/mw/project/685ab31bd471fb0c3b21607c)  
* 🛒 [**Python机器学习决策树，以客户流失预测分析为例**](https://www.heywhale.com/mw/project/68677c6eff953b31e4cf10ed)  
* 🛍️ [**Python机器学习K-means聚类，电商用户行为分析聚类**](https://www.heywhale.com/mw/project/686788fcff953b31e4d5fc89)  
* 🏦 [**Python机器学习支持向量机，信用卡欺诈检测**](https://www.heywhale.com/mw/project/686784344a5c763e5ce5158e)  
* 📧 [**Python机器学习朴素贝叶斯，垃圾邮件过滤**](https://www.heywhale.com/mw/project/686794b54a5c763e5cecf9a0)  

##  🕷️ Python爬虫系列  

* 🐝 [**Python爬虫实战，《哪吒2》豆瓣短评数据爬取**](https://www.heywhale.com/mw/project/67c1b6994cfa7d1e272dd59a)  
* 🐟️ [**Python爬虫实战，爬取《封神2》短评数据并可视化**](https://www.heywhale.com/mw/project/67c86cc28fded24f7f2d502a)  
* 🦢 [**Python爬虫实战，三步爬取豆瓣电影Top250数据**](https://www.heywhale.com/mw/project/67c30e417c7246ffce07da87)  
* 🦉 [**Python爬虫实战，爬取汽车之家数据并可视化**](https://www.heywhale.com/mw/project/67c86cac8fded24f7f2d4434)  
* 🐞 [**Python爬虫实战，爬取上海市天气并可视化**](https://www.heywhale.com/mw/project/67c8561c813696ecf4b408a5)  
* 🕸️ [**Python爬虫实战，天气数据爬取与地图可视化**](https://www.heywhale.com/mw/project/67d6770775fc52a789625667)  
* 🐳 [**Python爬虫实战，爬取旅游景点评论数据并可视化**](https://www.heywhale.com/mw/project/6760321ce8187b578b1cb2c5)  
* 🐠 [**Python爬虫实战，链家二手房数据轻松抓取！**](https://www.heywhale.com/mw/project/67602de2e8187b578b1b3adb)  
* 🦋 [**Python爬虫实战，一键爬取王者荣耀英雄头像**](https://www.heywhale.com/mw/project/67a77915414b53320edc8a49)  
* 🐼 [**Pandas爬取table数据并存储至SQL数据库**](https://www.heywhale.com/mw/project/67af51fdabfd5c89035df274)  
* 🐙 [**Python爬虫实战，TIOBE编程排行榜数据爬取**](https://www.heywhale.com/mw/project/67d1062924aa5d006f350d94)  
* 🐬 [**Python 爬虫实战：抓取北京大学2015-2024年录取分数线**](https://www.heywhale.com/mw/project/6841a042fb3243bdea723f3d)  
* 🐕️ [**Python爬虫实战，接入百度地图 API，精准获取上海公园数据并可视化**](https://www.heywhale.com/mw/project/67c99f32ac3a1f6f3ce8dadf)  

未完待续~ 😎😎😎  

***  

**点赞** ❤️、**Fork**、**收藏**、**评论** 💬 是作者创作的不懈动力，如果在代码运行过程中遇到问题，可在评论区留言 💬，解决你的代码问题 📝    

# 正文

本手册汇总了 30 道在数据科学、机器学习和科学计算岗位中常见的 NumPy 面试题，涵盖了核心概念、数组创建、索引与切片、数学运算、广播机制等常用操作，适用于 Python 初学者查漏补缺或面试准备。

## 一、基础与概念题（共5题）

### 1. 什么是 NumPy？为什么它在数据科学中如此重要？

**答**： NumPy (Numerical Python) 是 Python 中用于科学计算的基础包。它提供了一个强大的 N 维数组对象 (ndarray)，以及用于处理这些数组的各种函数。  

**详细说明**：  

- 性能： NumPy 的核心功能是用 C 语言实现的，其数组操作比纯 Python 的列表操作快得多，尤其是在处理大规模数据时。  
- 内存效率： NumPy 数组在内存中是连续存储的，相比 Python 列表，占用的空间更少。  
- 生态系统基石： 它是整个 Python 数据科学生态系统（如 Pandas, SciPy, Scikit-learn, Matplotlib）的基石，这些库都严重依赖 NumPy 的 ndarray 对象。  
- 功能丰富： 提供了大量的数学函数，包括线性代数、傅里叶变换和随机数生成等。

In [1]:
import numpy as np
import time

# Python 列表
list_a = range(1000000)
list_b = range(1000000)

start_time = time.time()
list_c = [a + b for a, b in zip(list_a, list_b)]
print(f"Python 列表求和耗时: {time.time() - start_time:.6f} 秒")

# NumPy 数组
arr_a = np.arange(1000000)
arr_b = np.arange(1000000)

start_time = time.time()
arr_c = arr_a + arr_b
print(f"NumPy 数组求和耗时: {time.time() - start_time:.6f} 秒")

Python 列表求和耗时: 0.155078 秒
NumPy 数组求和耗时: 0.003926 秒


### 2. NumPy 的核心数据结构是什么？它与 Python 列表有何不同？

**答**： NumPy 的核心数据结构是 ndarray（N-dimensional array，N维数组）。  

**主要区别**：  

- 数据类型： ndarray 是同质性的，即数组中所有元素的数据类型必须相同。而 Python 列表是异质性的，可以包含不同类型的元素。  
- 性能与内存： ndarray 在性能和内存使用上远优于 Python 列表，因为它底层使用 C 实现，并且数据在内存中是连续存储的。  
- 算术运算： NumPy 数组支持向量化运算，可以直接对整个数组进行数学运算，而 Python 列表需要通过循环实现。

In [4]:
# 1. 数据类型
arr = np.array([1, 2, 3])      # 正确，所有元素都是整数
# arr = np.array([1, 'a', 3.0]) # 会将所有元素统一转换为字符串类型

my_list = [1, 'a', 3.0]       # 正确，Python 列表可以存储不同类型

# 2. 算术运算
arr_doubled = arr * 2           # 向量化运算，结果为 [2, 4, 6]
arr_doubled

my_list_doubled = my_list * 2  # 列表的 * 操作是复制，结果为 [1, 'a', 3.0, 1, 'a', 3.0]
my_list_doubled

[1, 'a', 3.0, 1, 'a', 3.0]

### 3. 什么是 NumPy 的 axis 轴？请解释 axis=0 和 axis=1 的区别。

**答**： axis 参数定义了函数沿哪个维度（轴）进行运算。在一个二维数组（矩阵）中：  

- axis=0 表示沿着行的方向进行操作，即对每一列进行计算。  
- axis=1 表示沿着列的方向进行操作，即对每一行进行计算。  

**详细说明**：  

可以将 axis=0 理解为“向下”操作，axis=1 理解为“向右”操作。这个概念可以扩展到更高维度。例如，在一个三维数组中，axis=0 代表深度，axis=1 代表行，axis=2 代表列。

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# 求和操作
print("原始数组:\n", arr)
print("沿 axis=0 求和 (对每列求和):", arr.sum(axis=0))  # [1+4, 2+5, 3+6] -> [5, 7, 9]
print("沿 axis=1 求和 (对每行求和):", arr.sum(axis=1))  # [1+2+3, 4+5+6] -> [6, 15]

# 删除操作
print("删除第一列 (axis=1):\n", np.delete(arr, 0, axis=1))

原始数组:
 [[1 2 3]
 [4 5 6]]
沿 axis=0 求和 (对每列求和): [5 7 9]
沿 axis=1 求和 (对每行求和): [ 6 15]
删除第一列 (axis=1):
 [[2 3]
 [5 6]]


### 4. 什么是 NumPy 的广播机制？

**答**： 广播是 NumPy 在处理不同形状的数组进行算术运算时的一套规则。它可以在不显式复制数据的情况下，将较小的数组“广播”到较大数组的形状，从而实现元素级的运算。  

**广播规则**：  

- 如果两个数组的维度数不同，那么在维度较小的数组的形状前面补 1，直到维度数相同。  
- 如果两个数组在某个维度上的大小不一致，但其中一个为 1，那么就将大小为 1 的那个维度扩展，以匹配另一个数组的维度大小。  
- 如果两个数组在任何一个维度上的大小都不匹配且不为 1，则会引发错误。

In [7]:
# 场景：一个 3x3 的矩阵加上一个 1x3 的向量
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30])

# 最后进行元素级相加
result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### 5. 什么是 NumPy 的通用函数？

**答**： 通用函数（Universal Function）是一种对 ndarray 中的元素进行逐元素操作的函数。这些函数是 NumPy 中的核心，因为它们以编译后的 C 代码速度执行，非常高效。  

**详细说明**：  

- 常见的 ufunc 包括数学运算（np.add, np.subtract），三角函数（np.sin, np.cos），以及逻辑运算（np.logical_and）等。  
- ufunc 支持广播机制，可以处理不同形状的输入数组。

In [8]:
arr = np.arange(0, np.pi, np.pi/4)

# 计算每个元素的 sin 值
result_sin = np.sin(arr)
print("Sin values:", result_sin)

# 计算每个元素的平方根
result_sqrt = np.sqrt(np.array([1, 4, 9, 16]))
print("Square roots:", result_sqrt)

Sin values: [0.         0.70710678 1.         0.70710678]
Square roots: [1. 2. 3. 4.]


## 二、数组创建与操作题（共10题）

### 6. 如何创建一个 NumPy 数组？请列举至少 3 种方法。

**答**：  

1. 从 Python 列表或元组创建： np.array()  
2. 创建序列数组： np.arange(start, stop, step)  
3. 创建等差序列： np.linspace(start, stop, num_points)  
4. 创建特殊数组： np.zeros(), np.ones(), np.eye()  
5. 创建随机数组： np.random.rand(), np.random.randn(), np.random.randint()

In [9]:
# 1. 从列表创建
arr1 = np.array([[1, 2], [3, 4]])

# 2. 使用 arange 创建
arr2 = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# 3. 使用 linspace 创建
arr3 = np.linspace(0, 1, 5) # [0., 0.25, 0.5, 0.75, 1.]

# 4. 创建一个 2x3 的全零矩阵
arr4 = np.zeros((2, 3))

# 5. 创建一个 3x3 的单位矩阵
arr5 = np.eye(3)

### 7. 如何查看 NumPy 数组的维度、形状、大小和数据类型？

**答**：  

* 维度（秩）：arr.ndim - 数组的轴数。  
* 形状：arr.shape - 一个元组，表示数组在每个维度上的大小。  
* 大小：arr.size - 数组中元素的总数，等于 shape 属性中元组元素的乘积。  
* 数据类型：arr.dtype - 描述数组中元素类型的对象。

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("维度 (ndim):", arr.ndim)     # 输出: 2
print("形状 (shape):", arr.shape)   # 输出: (2, 3)
print("大小 (size):", arr.size)       # 输出: 6
print("数据类型 (dtype):", arr.dtype) # 输出: int32 (或 int64, 取决于系统)

维度 (ndim): 2
形状 (shape): (2, 3)
大小 (size): 6
数据类型 (dtype): int64


### 8. reshape 和 resize 方法有什么区别？

**答**： 两者都可以改变数组的形状，但有本质区别：  

* reshape()： 返回一个具有新形状的新数组（视图），但不改变原始数组。  
* resize()： 就地修改原始数组的形状，不返回任何内容（返回 None）。  

**关键点**：  

* reshape 更常用，因为它不会破坏原始数据。  
* resize 会直接修改原数组，如果原始数据还需要使用，这可能是危险的。

In [11]:
arr = np.arange(6)
print("原始数组:", arr)

# reshape 不改变原数组
reshaped_arr = arr.reshape((2, 3))
print("Reshaped 数组:\n", reshaped_arr)
print("使用 reshape 后原始数组:", arr) # 原数组不变

# resize 就地修改原数组
arr.resize((2, 3))
print("使用 resize 后原始数组:\n", arr) # 原数组已改变

原始数组: [0 1 2 3 4 5]
Reshaped 数组:
 [[0 1 2]
 [3 4 5]]
使用 reshape 后原始数组: [0 1 2 3 4 5]
使用 resize 后原始数组:
 [[0 1 2]
 [3 4 5]]


### 9. 解释 NumPy 中的索引和切片，特别是花式索引。

**答**： NumPy 提供了比 Python 列表更强大的索引和切片机制。  

1. **基本切片**： 与 Python 列表类似，使用 start:stop:step 的方式获取数组的子集，返回的是原始数组的视图（View）。  
2. **高级索引**（Advanced Indexing）：  
  花式索引（Fancy Indexing）： 使用整数数组或列表作为索引，可以选取任意位置、任意顺序的元素。返回的是原始数组的副本（Copy）。  
  布尔索引（Boolean Indexing）： 使用布尔数组作为索引，选取对应位置为 True 的元素。返回的是原始数组的副本（Copy）。

In [12]:
arr = np.arange(10)

# 基本切片 (视图)
sub_arr = arr[2:5] # [2, 3, 4]

# 花式索引 (副本)
indices = [1, 5, 8]
fancy_indexed_arr = arr[indices] # [1, 5, 8]

# 布尔索引 (副本)
mask = arr > 5
bool_indexed_arr = arr[mask] # [6, 7, 8, 9]

### 10. 什么是 NumPy 数组的视图（View）和副本（Copy）？如何判断？

**答**：  

- 副本（Copy）： 是数组的一个完整、独立的拷贝。对副本的任何修改都不会影响原始数组。  
- 视图（View）： 是原始数组的一个“浅”拷贝，它与原始数组共享同一块数据内存。对视图的修改会直接反映在原始数组上。  

**如何判断**：  

- 可以通过访问 ndarray 的 base 属性来判断。如果一个数组是另一个数组的视图，它的 base 属性会指向原始数组；否则，base 属性为 None。  

**生成时机**：  

- 视图： 基本切片操作。  
- 副本： 显式调用 copy() 方法、花式索引、布尔索引。

In [13]:
arr = np.arange(5)

# 创建视图
view_arr = arr[1:3]
view_arr[0] = 99
print("修改视图后，原始数组:", arr) # [ 0 99  2  3  4]
print("视图的 base 属性:", view_arr.base is arr) # True

# 创建副本
copy_arr = arr.copy()
copy_arr[0] = -1
print("修改副本后，原始数组:", arr) # [ 0 99  2  3  4]
print("副本的 base 属性:", copy_arr.base) # None

修改视图后，原始数组: [ 0 99  2  3  4]
视图的 base 属性: True
修改副本后，原始数组: [ 0 99  2  3  4]
副本的 base 属性: None


### 11. 如何水平和垂直地堆叠两个 NumPy 数组？

**答**：  

- 垂直堆叠（Vertical Stack）： 使用 np.vstack() 或 np.concatenate() 并设置 axis=0 。它会沿着第一个轴（行）堆叠数组。  
- 水平堆叠（Horizontal Stack）： 使用 np.hstack() 或 np.concatenate() 并设置 axis=1 。它会沿着第二个轴（列）堆叠数组。  

**关键点**：  

- 使用 vstack 时，数组的列数必须相同。  
- 使用 hstack 时，数组的行数必须相同。

In [14]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

# 垂直堆叠
v_stack = np.vstack((a, b))
print("垂直堆叠:\n", v_stack)

# 水平堆叠
h_stack = np.hstack((a, b))
print("水平堆叠:\n", h_stack)

垂直堆叠:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
水平堆叠:
 [[1 4]
 [2 5]
 [3 6]]


### 12. 如何对一个 NumPy 数组进行排序？

**答**： NumPy 提供了两种主要的排序方式：  

- np.sort() 函数： 返回一个 新 的排好序的数组副本，不修改原始数组。  
- ndarray.sort() 方法： 就地排序 ，直接修改原始数组，不返回任何值。  

**扩展用法**：  

axis 参数可以指定沿着哪个轴进行排序。默认是升序排序。对于降序，可以先排序再反转，例如 np.sort(arr)[::-1] 。

In [15]:
arr = np.array([[3, 1, 2], [6, 4, 5]])

# np.sort() - 不改变原数组
sorted_arr_copy = np.sort(arr, axis=1)
print("使用 np.sort() 排序后:\n", sorted_arr_copy)
print("原数组不变:\n", arr)

# ndarray.sort() - 改变原数组
arr.sort(axis=0)
print("使用 arr.sort() 排序后，原数组改变:\n", arr)

使用 np.sort() 排序后:
 [[1 2 3]
 [4 5 6]]
原数组不变:
 [[3 1 2]
 [6 4 5]]
使用 arr.sort() 排序后，原数组改变:
 [[3 1 2]
 [6 4 5]]


### 13. 如何计算两个 NumPy 数组的矩阵乘法？

**答**： 有三种主要方式：  

* 使用 @ 运算符（Python 3.5+ 推荐）。  
* 使用 np.dot() 函数。  
* 使用 ndarray.dot() 方法。

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 1. 使用 @ 运算符
C1 = A @ B
print("使用 @ 的结果:\n", C1)

# 2. 使用 np.dot()
C2 = np.dot(A, B)
print("使用 np.dot() 的结果:\n", C2)

# 元素级乘法 (对比)
print("使用 * 的结果:\n", A * B)

使用 @ 的结果:
 [[19 22]
 [43 50]]
使用 np.dot() 的结果:
 [[19 22]
 [43 50]]
使用 * 的结果:
 [[ 5 12]
 [21 32]]


### 14. 如何在 NumPy 数组中找到唯一元素及其出现次数？

答： 使用 np.unique() 函数。  

- np.unique(arr) ： 返回数组中的唯一元素，并已排序。  
- np.unique(arr, return_counts=True) ： 返回一个元组，包含两个数组：一个是唯一元素数组，另一个是对应元素的出现次数数组。

In [17]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# 查找唯一元素
unique_elements = np.unique(arr)
print("唯一元素:", unique_elements)

# 查找唯一元素及其计数
unique_elements, counts = np.unique(arr, 
return_counts=True)
print("唯一元素:", unique_elements)
print("出现次数:", counts)

# 使用 zip 创建一个字典
print("元素计数对:", dict(zip(unique_elements, counts)))

唯一元素: [1 2 3 4]
唯一元素: [1 2 3 4]
出现次数: [1 2 3 4]
元素计数对: {1: 1, 2: 2, 3: 3, 4: 4}


### 15. 如何保存和加载 NumPy 数组？

**答**： NumPy 提供了多种文件 I/O 功能。  

- 保存为二进制文件：  
np.save('filename.npy', arr) ：保存单个数组到 .npy 格式的二进制文件中。  
np.savez('filename.npz', name1=arr1, name2=arr2) ：将多个数组保存到 .npz 格式的压缩文件中。  

- 加载二进制文件：  
np.load('filename.npy') ：从 .npy 文件加载数组。  
np.load('filename.npz') ：从 .npz 文件加载，返回一个类似字典的对象，可以通过键名访问数组。

In [18]:
# 保存单个数组
arr1 = np.arange(10)
np.save('my_array.npy', arr1)

# 加载单个数组
loaded_arr1 = np.load('my_array.npy')
print("加载的数组:", loaded_arr1)

# 保存多个数组
arr2 = np.ones((2, 2))
np.savez('my_archive.npz', x=arr1, y=arr2)

# 加载多个数组
archive = np.load('my_archive.npz')
print("加载的数组 x:", archive['x'])
print("加载的数组 y:", archive['y'])

加载的数组: [0 1 2 3 4 5 6 7 8 9]
加载的数组 x: [0 1 2 3 4 5 6 7 8 9]
加载的数组 y: [[1. 1.]
 [1. 1.]]


### 16. 如何在 NumPy 中生成随机数并设置随机种子？

**答**： NumPy 的 random 模块提供了丰富的函数来生成随机数。为了使随机结果可复现，可以使用 np.random.seed() 或创建一个 Generator 实例。  

- 设置全局种子（旧方法）：np.random.seed(seed_value)，这会影响所有后续的 np.random.* 调用。  
- 使用生成器（推荐方法）：rng = np.random.default_rng(seed_value)，创建一个独立的生成器实例，调用该实例的方法（如 rng.random(), rng.integers()）来生成随机数，这样不会影响全局的随机状态。

In [21]:
import numpy as np

# 设置随机种子
np.random.seed(42)

# 生成一个 2x3 的、在 [0, 1) 范围内的均匀分布随机数组
random_arr = np.random.random((2, 3))
print("使用传统方法生成的随机数组:\n", random_arr)

# 生成 5 个范围在 [1, 10] 内的随机整数
random_integers = np.random.randint(1, 11, size=5)
print("生成的随机整数:", random_integers)

# 验证可重复性
np.random.seed(42)
random_arr_legacy = np.random.random((2, 3))
print("\n使用相同种子再次生成的随机数组:\n", random_arr_legacy)
print("两次生成是否相同:", np.array_equal(random_arr, random_arr_legacy))

使用传统方法生成的随机数组:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
生成的随机整数: [8 5 4 8 8]

使用相同种子再次生成的随机数组:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
两次生成是否相同: True


### 17. 什么是向量化？为什么它在 NumPy 中很重要？

**答**： 向量化是指使用 NumPy 的内置函数和操作来直接处理整个数组，而不是使用显式的 Python 循环（for-loops）逐个处理元素。  

**重要性**：  

- 性能： 向量化操作通常是在编译后的 C 或 Fortran 代码中执行的，速度远快于解释执行的 Python 循环。  
- 代码简洁性： 向量化代码更简洁、更易读，也更接近标准的数学表示法。  
- 减少错误： 避免了手动编写循环可能引入的索引错误等问题。

In [22]:
import time

arr = np.arange(1_000_000)

# 非向量化方式 (使用循环)
start_time = time.time()
result_loop = np.zeros_like(arr)
for i in range(len(arr)):
    result_loop[i] = arr[i] * 2
print(f"循环耗时: {time.time() - start_time:.6f} 秒")

# 向量化方式
start_time = time.time()
result_vectorized = arr * 2
print(f"向量化耗时: {time.time() - start_time:.6f} 秒")

循环耗时: 0.318408 秒
向量化耗时: 0.003924 秒


### 18. 如何使用 np.where() 进行条件选择？

**答**： np.where() 是一个非常强大的函数，用于根据条件从两个数组中选择元素，或者直接返回满足条件的元素的索引。  

**语法**：np.where(condition, x, y)  

- condition：一个布尔数组。当 condition 中对应位置为 True 时，从 x 中取值。当 condition 中对应位置为 False 时，从 y 中取值。它等价于一个向量化的 if-else 语句。

In [26]:
arr = np.array([-2, -1, 0, 1, 2, 3])

# 示例 1: 将所有负数替换为 0，正数保持不变
result = np.where(arr < 0, 0, arr)
print("将负数替换为0:", result) # 输出: [0 0 0 1 2 3]

将负数替换为0: [0 0 0 1 2 3]


In [27]:
# 示例 2: 根据条件分配不同的值
# 将偶数替换为 -1，奇数替换为 1
result_even_odd = np.where(arr % 2 == 0, -1, 1)
print("奇偶替换:", result_even_odd) # 输出: [-1 1 -1 1 -1 1]

奇偶替换: [-1  1 -1  1 -1  1]


In [28]:
# 示例 3: 只传入 condition，返回满足条件的索引
indices = np.where(arr > 0)
print("大于0的元素的索引:", indices) # 输出: (array([3, 4, 5]),)

大于0的元素的索引: (array([3, 4, 5]),)


### 19. 如何展平一个多维 NumPy 数组？flatten() 和 ravel() 有什么区别？

**答**： 展平是指将一个多维数组转换成一个一维数组。NumPy 提供了两种主要的方法：ndarray.flatten() 和 np.ravel()。  

**主要区别**：  

- flatten()： 总是返回原始数组的一个副本（Copy）。对返回数组的修改不会影响原始数组。  
- ravel()： 通常返回原始数组的一个视图（View），除非在内存不连续的情况下才创建副本。它在可能的情况下会避免复制数据，因此速度更快，内存效率更高。

In [29]:
arr = np.array([[1, 2], [3, 4]])

# 使用 flatten (返回副本)
flattened_arr = arr.flatten()
flattened_arr[0] = 99
print("使用 flatten() 后，原始数组:", arr) # 不变

使用 flatten() 后，原始数组: [[1 2]
 [3 4]]


In [30]:
# 使用 ravel (返回视图)
raveled_arr = arr.ravel()
raveled_arr[0] = 99
print("使用 ravel() 后，原始数组:", arr) # 已改变

使用 ravel() 后，原始数组: [[99  2]
 [ 3  4]]


### 20. 如何处理 NumPy 数组中的缺失值（NaN）？

**答**： 在数据分析中，处理缺失值（Not a Number, NaN）是常见任务。NumPy 提供了专门的函数来识别和处理它们。  

**常用函数**：  

- np.isnan(arr)： 返回一个布尔数组，NaN 所在位置为 True，否则为 False。  
- np.nan_to_num(arr, nan=0.0)： 将 NaN 替换为指定的值（默认为 0）。  

聚合函数中的处理： 许多 NumPy 聚合函数（如 np.sum, np.mean）在遇到 NaN 时会返回 NaN。可以使用它们的 nan- 版本（如 np.nansum, np.nanmean）来忽略 NaN 值进行计算。

In [33]:
import numpy as np

arr = np.array([1, 2, np.nan, 4])

# 1. 查找 NaN
print("Is NaN:", np.isnan(arr))

# 2. 统计 NaN 的数量
print("Count of NaNs:", np.sum(np.isnan(arr)))

# 3. 替换 NaN - 旧版本兼容方法
# 方法1: 使用布尔索引
arr_no_nan = arr.copy()
arr_no_nan[np.isnan(arr_no_nan)] = -1
print("替换 NaN 后的数组 (方法1):", arr_no_nan)

# 方法2: 使用 np.where
arr_no_nan2 = np.where(np.isnan(arr), -1, arr)
print("替换 NaN 后的数组 (方法2):", arr_no_nan2)

# 4. 计算时忽略 NaN
print("Sum (忽略 NaN):", np.nansum(arr))
print("Mean (忽略 NaN):", np.nanmean(arr))

Is NaN: [False False  True False]
Count of NaNs: 1
替换 NaN 后的数组 (方法1): [ 1.  2. -1.  4.]
替换 NaN 后的数组 (方法2): [ 1.  2. -1.  4.]
Sum (忽略 NaN): 7.0
Mean (忽略 NaN): 2.3333333333333335


## 三、进阶与应用题（共10题）

### 21. 解释 NumPy 中的结构化数组

**答**： 结构化数组是一种特殊的 ndarray，它允许每个元素包含多个不同数据类型的字段，类似于 C 语言中的 struct 或 SQL 表中的一行记录。这使得 NumPy 能够以一种高效的方式存储异构数据。  

**应用场景**：  

从 CSV 文件或数据库中读取结构化数据。在需要将多种数据类型组合成一个记录单元时，提供一种比 Python 对象更节省内存的方式。

In [37]:
# 定义数据类型：包含一个字符串'name'，一个整数'age'，一个浮点数'height'
data_type = [('name', 'S10'), ('age', 'i4'), ('height', 'f8')]

# 创建结构化数组
people = np.array([('Alice', 25, 1.65), ('Bob', 30, 1.80)], dtype=data_type)

# 按字段名访问数据
print("所有人的姓名:", people['name'])
print("第一个人的年龄:", people[0]['age'])

所有人的姓名: [b'Alice' b'Bob']
第一个人的年龄: 25


### 22. np.array() 和 np.asarray() 有什么区别？

**答**： 两者都可以将输入转换为一个 NumPy 数组，但核心区别在于处理已经是 ndarray 的输入时的行为：  

- np.array()： 默认情况下，总是创建一个新的数组副本（Copy）。  
- np.asarray()： 如果输入本身已经是 ndarray，并且数据类型匹配，它将不会创建副本，而是直接返回原始数组的引用（视图）。

In [38]:
arr = np.arange(5)

# 使用 np.array()，创建副本
arr_copy = np.array(arr)
print("arr_copy is arr:", arr_copy is arr) # False

# 使用 np.asarray()，不创建副本
arr_view = np.asarray(arr)
print("arr_view is arr:", arr_view is arr) # True

arr_copy is arr: False
arr_view is arr: True


### 23. 如何使用 NumPy 的 linalg 模块进行线性代数运算？

**答**： NumPy 的 linalg 子模块提供了进行线性代数运算所需的核心函数，例如计算行列式、求逆矩阵、解线性方程组等。  

**核心函数**：  

- np.linalg.inv(A)： 计算矩阵 A 的逆。  
- np.linalg.det(A)： 计算矩阵 A 的行列式。  
- np.linalg.solve(A, b)： 求解线性方程组 Ax = b。  
- np.linalg.eig(A)： 计算矩阵 A 的特征值和特征向量。

In [39]:
A = np.array([[2, 1], [1, 1]])
b = np.array([4, 3])

# 1. 求逆矩阵
A_inv = np.linalg.inv(A)
print("逆矩阵 A_inv:\n", A_inv)

# 2. 求解线性方程组 Ax = b
x = np.linalg.solve(A, b)
print("方程组的解 x:", x) # [1. 2.]

# 3. 验证解
print("A @ x:", A @ x) # 结果应接近 b

逆矩阵 A_inv:
 [[ 1. -1.]
 [-1.  2.]]
方程组的解 x: [1. 2.]
A @ x: [4. 3.]


### 24. 解释 NumPy 中的掩码数组

**答**： 掩码数组模块 (numpy.ma) 提供了一种方便的方式来处理包含无效或缺失数据的数组。它通过一个伴随的布尔掩码数组来“屏蔽”掉某些元素，使它们在计算中被忽略。  

**与 NaN 的区别**：  

NaN 是一种特定的浮点数值，会“污染”计算（例如 np.sum([1, np.nan]) 结果是 nan）。掩码数组提供了一种更通用的机制，可以屏蔽任何数据类型的元素，并且被屏蔽的元素不会参与计算。

In [40]:
import numpy.ma as ma

arr = np.array([1, 2, -1, 4, 5])

# 创建一个掩码数组，其中 -1 被视为无效
masked_arr = ma.masked_where(arr == -1, arr)
print("掩码数组:", masked_arr)

# 计算均值时，被屏蔽的元素会被忽略
print("Mean of masked array:", masked_arr.mean()) # (1+2+4+5)/4 = 3.0
print("Mean of original array:", arr.mean()) # (1+2-1+4+5)/5 = 2.2

掩码数组: [1 2 -- 4 5]
Mean of masked array: 3.0
Mean of original array: 2.2


### 25. NumPy 如何处理内存布局

**答**： NumPy 数组在内存中可以按两种不同的顺序存储多维数据：  

- C order (行主序): C 语言风格，也是 NumPy 的默认设置。数据按行连续存储。访问一行中的元素速度很快。  
- F order (列主序): Fortran 语言风格。数据按列连续存储。访问一列中的元素速度很快。  

这个属性可以通过数组的 flags 查看 (arr.flags.c_contiguous 或 arr.flags.f_contiguous)。在创建或重塑数组时，可以通过 order='C' 或 order='F' 参数来指定。

In [41]:
# 默认是 C order
arr_c = np.zeros((1000, 1000), order='C')

# 指定为 F order
arr_f = np.zeros((1000, 1000), order='F')

print("C order array is C-contiguous:", arr_c.flags.c_contiguous)
print("F order array is F-contiguous:", arr_f.flags.f_contiguous)

C order array is C-contiguous: True
F order array is F-contiguous: True


### 26. 什么是爱因斯坦求和约定？

**答**： np.einsum 是 NumPy 中一个极其强大和灵活的函数，它使用爱因斯坦求和约定表示法来执行多维数组的乘法和求和运算。通过一个简洁的字符串表达式，可以实现点积、外积、矩阵乘法、转置、张量缩并等多种操作。

In [42]:
A = np.arange(9).reshape(3, 3)
B = np.ones((3, 3))

# 1. 矩阵乘法: 'ij,jk->ik'
# i,j 是 A 的索引，j,k 是 B 的索引，输出是 i,k
# 重复的 j 轴被求和
C = np.einsum('ij,jk->ik', A, B)
print("矩阵乘法:\n", C)

# 2. 矩阵转置: 'ij->ji'
print("矩阵转置:\n", np.einsum('ij->ji', A))

# 3. 对角线求和 (迹): 'ii->'
print("矩阵的迹:", np.einsum('ii->', A))

矩阵乘法:
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]
矩阵转置:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
矩阵的迹: 12


### 27. 如何在 NumPy 中处理日期和时间数据？

答： NumPy 通过 datetime64 和 timedelta64 数据类型提供了对日期和时间的高效支持。这使得我们可以像处理数值一样对时间序列数据进行向量化操作。

In [43]:
# 创建一个日期
date = np.datetime64('2024-01-01')

# 创建一个日期范围
date_range = np.arange('2024-01-01', '2024-01-10', dtype='datetime64[D]')
print("日期范围:\n", date_range)

# 日期运算
one_day = np.timedelta64(1, 'D')
next_day = date + one_day
print("第二天:", next_day)

# 计算两个日期之间的天数
days_diff = np.datetime64('2024-02-01') - np.datetime64('2024-01-01')
print("相差天数:", days_diff)

日期范围:
 ['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07' '2024-01-08' '2024-01-09']
第二天: 2024-01-02
相差天数: 31 days


### 28. np.vectorize 的作用是什么？什么时候应该使用它？

**答**： np.vectorize 是一个便利函数，它可以将一个普通的、不支持向量化操作的 Python 函数转换成一个可以在 NumPy 数组上进行元素级操作的“向量化”函数。  

**重要提醒**： np.vectorize 的主要目的是为了方便，其底层仍然是使用 Python 循环，并不会带来性能上的提升。它只是提供了一个简洁的语法来避免手动编写 for 循环。  

**使用场景**：  

- 当你有一个无法直接应用于 NumPy 数组的复杂 Python 函数，并且希望以一种简洁的方式将其应用于数组的每个元素时。  
- 当代码的可读性和简洁性比极致的性能更重要时。

In [44]:
# 一个普通的 Python 函数
def my_func(x):
    if x > 0:
        return x
    else:
        return -x
        
# 使用 np.vectorize 转换为向量化函数
vec_func = np.vectorize(my_func)

# 对数组进行元素级操作
arr = np.array([-1, 2, -3, 4, -5])
print("原始数组:", arr)
print("转换后的数组:", vec_func(arr))

原始数组: [-1  2 -3  4 -5]
转换后的数组: [1 2 3 4 5]


### 29. 如何在 NumPy 中进行广播？

**答**： 广播是 NumPy 中一个强大的机制，它允许在不同形状的数组之间进行元素级操作，而无需进行显式的复制。这使得代码更加简洁和高效。

In [49]:
# 1.数据标准化，将每列数据标准化（减去均值，除以标准差）
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

mean = data.mean(axis=0)    # 每列的均值 [4, 5, 6]
std = data.std(axis=0)      # 每列的标准差

normalized = (data - mean) / std
print("标准化后的数据:\n", normalized)

# 2.使用广播计算外积
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 传统方法
outer_product = np.outer(a, b)
print("外积 (传统方法):\n", outer_product)

# 广播方法
outer_broadcast = a[:, np.newaxis] * b  # a变为列向量(3,1), b广播为(3,3)
print("外积 (广播方法):\n", outer_broadcast)

# 3.生成网格坐标
x = np.linspace(0, 1, 3)  # [0, 0.5, 1]
y = np.linspace(0, 1, 4)  # [0, 0.333, 0.666, 1]

# 使用广播生成网格
X, Y = np.meshgrid(x, y)  # 传统方法
print("Meshgrid X:\n", X)
print("Meshgrid Y:\n", Y)

# 使用广播（更高效）
X_broadcast = x[np.newaxis, :]  # 形状: (1, 3)
Y_broadcast = y[:, np.newaxis]  # 形状: (4, 1)

# 计算距离场
distance = np.sqrt(X_broadcast**2 + Y_broadcast**2)
print("距离场:\n", distance)

标准化后的数据:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
外积 (传统方法):
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
外积 (广播方法):
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Meshgrid X:
 [[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
Meshgrid Y:
 [[0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667]
 [1.         1.         1.        ]]
距离场:
 [[0.         0.5        1.        ]
 [0.33333333 0.60092521 1.05409255]
 [0.66666667 0.83333333 1.20185043]
 [1.         1.11803399 1.41421356]]


### 30. 什么是 NumPy 的内存映射数组？它有什么优势？

**答：** 内存映射数组是一种将磁盘上的二进制文件“映射”到内存中的 `ndarray` 对象的技术。这意味着数组的数据保留在磁盘上，而不是加载到 RAM 中。  

**主要优势：**  
1.  **处理超大文件：** 允许你操作远大于可用 RAM 的数据集。你可以像操作普通 NumPy 数组一样对文件的片段进行读写，而操作系统会负责在后台处理数据的换入和换出。  
2.  **数据持久化与共享：** 对内存映射数组的任何修改都会被直接写回磁盘文件，实现了数据的自动保存。此外，多个进程可以映射同一个文件来共享和修改数据。

In [45]:
# 创建一个 1000x1000 的内存映射数组 
# 数据将存储在
mem_arr = np.memmap('my_mapped_array.dat', dtype='float64', mode='w+', shape=(1000, 1000))

# 像普通数组一样操作
mem_arr[0, :] = 42.0
mem_arr.flush() # 确保更改已写入磁盘

# 稍后可以重新加载它
loaded_arr = np.memmap('my_mapped_array.dat', dtype='float64', mode='r', shape=(1000, 1000))
print("从文件中加载的值:", loaded_arr[0, 0])

从文件中加载的值: 42.0


NumPy 是 Python 数据科学领域不可或缺的基石。掌握其核心概念，如 `ndarray`、广播机制、向量化和内存管理，对于编写高效、简洁和强大的数据处理代码至关重要。本手册涵盖了从基础概念到高级应用的 30 个常见面试题，旨在帮助你巩固知识、发现盲点。希望这份手册能成为你学习和面试路上的得力助手。祝你面试成功！

**推荐阅读** 📖 [**Python数据分析合集：零基础，让你轻松搞定数据分析！**](https://www.heywhale.com/mw/project/67a5b279414b53320ea67ef8)  